version: '3'

services:
    react_host:
        container_name: react_host
        build:
            context: .
            dockerfile: Dockerfile.dev
        ports:
            - 3001:3000
        volumes:
            - ./app/node_modules 
            - .:/app